# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\PyQt5Code\Chapter03\MainFrom.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 334)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setObjectName("menu_E")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiondakai1 = QtWidgets.QAction(MainWindow)
        self.actiondakai1.setObjectName("actiondakai1")
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.EditAction = QtWidgets.QAction(MainWindow)
        self.EditAction.setObjectName("EditAction")
        self.menu_F.addAction(self.actiondakai1)
        self.menu_F.addAction(self.actionnew)
        self.menu_F.addAction(self.actionclose)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.EditAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(F)"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑(E)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiondakai1.setText(_translate("MainWindow", "打开"))
        self.actiondakai1.setToolTip(_translate("MainWindow", "打开"))
        self.actiondakai1.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionnew.setText(_translate("MainWindow", "新建"))
        self.actionnew.setToolTip(_translate("MainWindow", "新建"))
        self.actionnew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionclose.setText(_translate("MainWindow", "关闭"))
        self.actionclose.setToolTip(_translate("MainWindow", "关闭"))
        self.actionclose.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.EditAction.setText(_translate("MainWindow", "添加窗口"))
        self.EditAction.setToolTip(_translate("MainWindow", "添加窗口"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
