# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\PyQt5Code\Chapter03\MainWinSignalSlog01.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_closeWinBtn(object):
    def setupUi(self, closeWinBtn):
        closeWinBtn.setObjectName("closeWinBtn")
        closeWinBtn.resize(643, 526)
        self.pushButton = QtWidgets.QPushButton(closeWinBtn)
        self.pushButton.setGeometry(QtCore.QRect(130, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(closeWinBtn)
        self.pushButton.clicked.connect(closeWinBtn.close)
        QtCore.QMetaObject.connectSlotsByName(closeWinBtn)

    def retranslateUi(self, closeWinBtn):
        _translate = QtCore.QCoreApplication.translate
        closeWinBtn.setWindowTitle(_translate("closeWinBtn", "Form"))
        self.pushButton.setText(_translate("closeWinBtn", "关闭窗口"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    closeWinBtn = QtWidgets.QWidget()
    ui = Ui_closeWinBtn()
    ui.setupUi(closeWinBtn)
    closeWinBtn.show()
    sys.exit(app.exec_())
